#!/bin/bash

echo "" > mataddTest.out

for i in {0..3}; do
   echo "test loop unroll ${i}:" | tee -a mataddTest.out
   make clean
   make 
   perf stat ./matadd i2^${i} 2>> mataddTest.out
done

make clean

exit 0
