#!/bin/bash

echo "" > mataddTest.out

for i in {0..3}; do
   echo "test O${i}:" | tee -a mataddTest.out
   make clean
   make matadd_${i}
   perf stat ./matadd 2>> mataddTest.out
done

make clean

exit 0
