#!/bin/bash

echo "" > mataddTest.out

for i in {1,2,4,8}; do
   echo "test loop unroll ${i}:" | tee -a mataddTest.out
   make clean
   make 
   perf stat ./matadd ${i} 2>> mataddTest.out
done

make clean

exit 0
